planning_plugins:
  - ompl_interface/OMPLPlanner

request_adapters: "default_planning_request_adapters/ResolveConstraintFrames default_planning_request_adapters/ValidateWorkspaceBounds default_planning_request_adapters/CheckStartStateBounds default_planning_request_adapters/CheckStartStateCollision"

xarm7:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRTstar
    - PRM

hitbot_arm:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRTstar
    - PRM

planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.0
  RRTstar:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
  PRM:
    type: geometric::PRM
    max_nearest_neighbors: 10
